title = "Alpaca Sample Driver (Rotator)"

[network]
ip_address = ''             # Any address
port = 5555

[server]
location = 'Anywhere on Earth'  # Anything you want here
verbose_driver_exceptions = true

[device]
can_reverse = true
step_size = 1.0
steps_per_sec = 6
sync_write_connected = true     # True to emulate sync Connected = true (for Conform)

[logging]
log_level = 'INFO'
log_to_stdout = false
max_size_mb = 5
num_keep_logs = 10
